spring:
  datasource:
    password: 5654
    username: postgres
    url: jdbc:postgresql://localhost:5432/market?currentSchemaName=market
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  banner:
    image:
      location: classpath:banner.txt

api:
  info:
    title: Market
    description: This is automatic panel for market
    version: 1.0
    terms-of-service: https://market.uz
    contact-name: market.uz
    contact-email: bestteam@gmail.com
    contact-url: https://cotton.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: 8080
    url: boom.uz

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs